import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import {
  AgentCapabilities, AgentTask, CompleteTaskRequest, EnrollAgentRequest, EnrollAgentResponse, Environment,
  EnvironmentSpec, HeartbeatRequest, NebulaCertificateRequest, NebulaCertificateResponse, Operation, OperationEvent, Problem, TaskEventRequest, WorkloadManifest,
  WorkloadPackage, WorkloadVersion
} from "../src/index.js";

const root = resolve(import.meta.dirname, "..");
const generated = resolve(root, "generated");
const schemas = { AgentCapabilities, AgentTask, CompleteTaskRequest, EnrollAgentRequest, EnrollAgentResponse, Environment, EnvironmentSpec, HeartbeatRequest, NebulaCertificateRequest, NebulaCertificateResponse, Operation, OperationEvent, Problem, TaskEventRequest, WorkloadManifest, WorkloadPackage, WorkloadVersion };
const ref = (name: keyof typeof schemas) => ({ $ref: `#/components/schemas/${name}` });
const openapi = {
  openapi: "3.1.0", info: { title: "Infractory control plane", version: "0.1.0" },
  servers: [{ url: "/" }],
  paths: {
    "/api/v1/environments": {
      get: { operationId: "listEnvironments", responses: { "200": { description: "Environment page" } } },
      post: { operationId: "createEnvironment", responses: { "201": { description: "Created", content: { "application/json": { schema: ref("Environment") } } } } }
    },
    "/api/v1/environments/{id}/plan": { post: { operationId: "planEnvironment", responses: { "202": { description: "Queued", content: { "application/json": { schema: ref("Operation") } } } } } },
    "/api/v1/environments/{id}/apply": { post: { operationId: "applyEnvironment", responses: { "202": { description: "Queued", content: { "application/json": { schema: ref("Operation") } } } } } },
    "/api/v1/environments/{id}/destroy": { post: { operationId: "destroyEnvironment", responses: { "202": { description: "Queued", content: { "application/json": { schema: ref("Operation") } } } } } },
    "/api/v1/operations/{id}": { get: { operationId: "getOperation", responses: { "200": { description: "Operation", content: { "application/json": { schema: ref("Operation") } } } } } },
    "/api/v1/operations/{id}/events": { get: { operationId: "streamOperationEvents", responses: { "200": { description: "SSE stream or event page" } } } },
    "/agent/v1/enroll": { post: { operationId: "enrollAgent", requestBody: { content: { "application/json": { schema: ref("EnrollAgentRequest") } } }, responses: { "200": { description: "Enrolled", content: { "application/json": { schema: ref("EnrollAgentResponse") } } } } } },
    "/agent/v1/heartbeat": { post: { operationId: "heartbeat", security: [{ deviceToken: [] }], responses: { "204": { description: "Accepted" } } } },
    "/agent/v1/tasks/next": { get: { operationId: "nextAgentTask", security: [{ deviceToken: [] }], responses: { "200": { description: "Leased task", content: { "application/json": { schema: ref("AgentTask") } } }, "204": { description: "No task" } } } }
    ,"/agent/v1/nebula-certificate-requests": { post: { operationId: "requestNebulaCertificate", security: [{ deviceToken: [] }], requestBody: { content: { "application/json": { schema: ref("NebulaCertificateRequest") } } }, responses: { "200": { description: "Signed certificate", content: { "application/json": { schema: ref("NebulaCertificateResponse") } } } } } }
  },
  components: { schemas, securitySchemes: { deviceToken: { type: "http", scheme: "bearer", bearerFormat: "opaque" } } }
};
const openapiText = `${JSON.stringify(openapi, null, 2)}\n`;
const agentSchemaText = JSON.stringify({ AgentCapabilities, AgentTask, CompleteTaskRequest, EnrollAgentRequest, EnrollAgentResponse, HeartbeatRequest, NebulaCertificateRequest, NebulaCertificateResponse, TaskEventRequest });
const digest = createHash("sha256").update(agentSchemaText).digest("hex");
const goText = `// Code generated by @infractory/contracts. DO NOT EDIT.
// Contract digest: ${digest}
package protocol

import (
\t"encoding/json"
\t"time"
)

type Capabilities struct {
\tOS                 string   \`json:"os"\`
\tArchitecture       string   \`json:"architecture"\`
\tDockerVersion      *string  \`json:"dockerVersion"\`
\tComposeVersion     *string  \`json:"composeVersion"\`
\tTunAvailable       bool     \`json:"tunAvailable"\`
\tNTPSynchronized    bool     \`json:"ntpSynchronized"\`
\tClockOffsetSeconds *float64 \`json:"clockOffsetSeconds"\`
}

type EnrollRequest struct {
\tToken        string       \`json:"token"\`
\tPublicKey    string       \`json:"publicKey"\`
\tCapabilities Capabilities \`json:"capabilities"\`
}

type EnrollResponse struct {
\tNodeID                   string    \`json:"nodeId"\`
\tDeviceToken              string    \`json:"deviceToken"\`
\tExpiresAt                time.Time \`json:"expiresAt"\`
\tHeartbeatIntervalSeconds int       \`json:"heartbeatIntervalSeconds"\`
}

type RotateDeviceTokenResponse struct {
\tDeviceToken        string    \`json:"deviceToken"\`
\tExpiresAt          time.Time \`json:"expiresAt"\`
\tOldTokenValidUntil time.Time \`json:"oldTokenValidUntil"\`
}

type HeartbeatRequest struct {
\tGeneration   int64          \`json:"generation"\`
\tAgentVersion string         \`json:"agentVersion"\`
\tCapabilities Capabilities   \`json:"capabilities"\`
\tObservation  map[string]any \`json:"observation"\`
}

type Task struct {
\tTaskID         string          \`json:"taskId"\`
\tActionKey      string          \`json:"actionKey"\`
\tNodeGeneration int64           \`json:"nodeGeneration"\`
\tAttempt        int             \`json:"attempt"\`
\tLeaseToken     string          \`json:"leaseToken"\`
\tLeaseExpiresAt time.Time       \`json:"leaseExpiresAt"\`
\tDeadline       time.Time       \`json:"deadline"\`
\tKind           TaskKind        \`json:"kind"\`
\tPayload        json.RawMessage \`json:"payload"\`
}

type TaskKind string

const (
\tTaskInspectHost         TaskKind = "InspectHost"
\tTaskEnsurePrerequisites TaskKind = "EnsurePrerequisites"
\tTaskEnsureNebula        TaskKind = "EnsureNebula"
\tTaskApplyWorkload       TaskKind = "ApplyWorkload"
\tTaskRemoveWorkload      TaskKind = "RemoveWorkload"
\tTaskCollectObservation  TaskKind = "CollectObservation"
\tTaskCleanupNode         TaskKind = "CleanupNode"
\tTaskTailWorkloadLogs    TaskKind = "TailWorkloadLogs"
\tTaskRotateDeviceToken   TaskKind = "RotateDeviceToken"
\tTaskUpgradeAgent        TaskKind = "UpgradeAgent"
)

type TaskEventRequest struct {
\tLeaseToken string \`json:"leaseToken"\`
\tSequence   int    \`json:"sequence"\`
\tLevel      string \`json:"level"\`
\tMessage    string \`json:"message"\`
}

type CompleteTaskRequest struct {
\tLeaseToken   string         \`json:"leaseToken"\`
\tOutcome      string         \`json:"outcome"\`
\tResult       map[string]any \`json:"result"\`
\tErrorCode    string         \`json:"errorCode,omitempty"\`
\tErrorMessage string         \`json:"errorMessage,omitempty"\`
}

type EnsurePrerequisitesPayload struct {
\tDocker bool \`json:"docker"\`
\tNebula bool \`json:"nebula"\`
}

type EnsureNebulaPayload struct {
\tEnvironmentID string   \`json:"environmentId"\`
\tCIDR          string   \`json:"cidr"\`
\tLighthouse    bool     \`json:"lighthouse"\`
\tGroups        []string \`json:"groups"\`
\tConfigYAML    string   \`json:"config,omitempty"\`
\tCACertificate string   \`json:"caCertificate,omitempty"\`
\tCertificate   string   \`json:"certificate,omitempty"\`
}

type SecretFile struct {
\tTarget        string \`json:"target"\`
\tContentBase64 string \`json:"contentBase64"\`
}

type AllowedPort struct {
\tProtocol     string   \`json:"protocol"\`
\tPort         int      \`json:"port"\`
\tAllowedCIDRs []string \`json:"allowedCidrs"\`
}

type Probe struct {
\tKind           string \`json:"kind"\`
\tTarget         string \`json:"target"\`
\tTimeoutSeconds int    \`json:"timeoutSeconds"\`
}

type ApplyWorkloadPayload struct {
\tEnvironmentID  string            \`json:"environmentId"\`
\tDeploymentID   string            \`json:"deploymentId"\`
\tGeneration     int64             \`json:"generation"\`
\tComposeYAML    string            \`json:"composeYaml"\`
\tResolvedImages map[string]string \`json:"resolvedImages,omitempty"\`
\tAllowedPorts   []AllowedPort     \`json:"allowedPorts,omitempty"\`
\tSecretFiles    []SecretFile      \`json:"secretFiles,omitempty"\`
\tProbes         []Probe           \`json:"probes,omitempty"\`
\tTimeoutSeconds int               \`json:"timeoutSeconds,omitempty"\`
}

type CollectObservationPayload struct {
\tIncludeWorkloads bool \`json:"includeWorkloads"\`
}

type RemoveWorkloadPayload struct {
\tDeploymentID       string \`json:"deploymentId"\`
\tRemoveOwnedVolumes bool   \`json:"removeOwnedVolumes"\`
}

type CleanupNodePayload struct {
\tEnvironmentID string \`json:"environmentId"\`
}

type TailWorkloadLogsPayload struct {
\tDeploymentID string     \`json:"deploymentId"\`
\tSince        *time.Time \`json:"since,omitempty"\`
}

type UpgradeAgentPayload struct {
\tVersion string \`json:"version"\`
\tURL     string \`json:"url"\`
\tSHA256  string \`json:"sha256"\`
}
`;

async function emit(path: string, content: string, check: boolean): Promise<void> {
  if (check) {
    const current = await readFile(path, "utf8").catch(() => "");
    if (current !== content) throw new Error(`${path} is stale; run pnpm --filter @infractory/contracts generate`);
    return;
  }
  await mkdir(dirname(path), { recursive: true }); await writeFile(path, content);
}

const check = process.argv.includes("--check");
await emit(resolve(generated, "openapi.json"), openapiText, check);
await emit(resolve(generated, "contract.sha256"), `${digest}\n`, check);
await emit(resolve(root, "../../apps/agent/internal/protocol/types.gen.go"), goText, check);
