// Code generated by @infractory/contracts. DO NOT EDIT.
// Contract digest: 32bebe90e2dab73a8d1cdc28da714043a977393c20ddfeb8cccf5318a86612ec
package protocol

import (
	"encoding/json"
	"time"
)

type Capabilities struct {
	OS                 string   `json:"os"`
	Architecture       string   `json:"architecture"`
	DockerVersion      *string  `json:"dockerVersion"`
	ComposeVersion     *string  `json:"composeVersion"`
	TunAvailable       bool     `json:"tunAvailable"`
	NTPSynchronized    bool     `json:"ntpSynchronized"`
	ClockOffsetSeconds *float64 `json:"clockOffsetSeconds"`
}

type EnrollRequest struct {
	Token        string       `json:"token"`
	PublicKey    string       `json:"publicKey"`
	Capabilities Capabilities `json:"capabilities"`
}

type EnrollResponse struct {
	NodeID                   string    `json:"nodeId"`
	DeviceToken              string    `json:"deviceToken"`
	ExpiresAt                time.Time `json:"expiresAt"`
	HeartbeatIntervalSeconds int       `json:"heartbeatIntervalSeconds"`
}

type RotateDeviceTokenResponse struct {
	DeviceToken        string    `json:"deviceToken"`
	ExpiresAt          time.Time `json:"expiresAt"`
	OldTokenValidUntil time.Time `json:"oldTokenValidUntil"`
}

type HeartbeatRequest struct {
	Generation   int64          `json:"generation"`
	AgentVersion string         `json:"agentVersion"`
	Capabilities Capabilities   `json:"capabilities"`
	Observation  map[string]any `json:"observation"`
}

type Task struct {
	TaskID         string          `json:"taskId"`
	ActionKey      string          `json:"actionKey"`
	NodeGeneration int64           `json:"nodeGeneration"`
	Attempt        int             `json:"attempt"`
	LeaseToken     string          `json:"leaseToken"`
	LeaseExpiresAt time.Time       `json:"leaseExpiresAt"`
	Deadline       time.Time       `json:"deadline"`
	Kind           TaskKind        `json:"kind"`
	Payload        json.RawMessage `json:"payload"`
}

type TaskKind string

const (
	TaskInspectHost         TaskKind = "InspectHost"
	TaskEnsurePrerequisites TaskKind = "EnsurePrerequisites"
	TaskEnsureNebula        TaskKind = "EnsureNebula"
	TaskApplyWorkload       TaskKind = "ApplyWorkload"
	TaskRemoveWorkload      TaskKind = "RemoveWorkload"
	TaskCollectObservation  TaskKind = "CollectObservation"
	TaskCleanupNode         TaskKind = "CleanupNode"
	TaskTailWorkloadLogs    TaskKind = "TailWorkloadLogs"
	TaskRotateDeviceToken   TaskKind = "RotateDeviceToken"
	TaskUpgradeAgent        TaskKind = "UpgradeAgent"
)

type TaskEventRequest struct {
	LeaseToken string `json:"leaseToken"`
	Sequence   int    `json:"sequence"`
	Level      string `json:"level"`
	Message    string `json:"message"`
}

type CompleteTaskRequest struct {
	LeaseToken   string         `json:"leaseToken"`
	Outcome      string         `json:"outcome"`
	Result       map[string]any `json:"result"`
	ErrorCode    string         `json:"errorCode,omitempty"`
	ErrorMessage string         `json:"errorMessage,omitempty"`
}

type EnsurePrerequisitesPayload struct {
	Docker bool `json:"docker"`
	Nebula bool `json:"nebula"`
}

type EnsureNebulaPayload struct {
	EnvironmentID string   `json:"environmentId"`
	CIDR          string   `json:"cidr"`
	Lighthouse    bool     `json:"lighthouse"`
	Groups        []string `json:"groups"`
	ConfigYAML    string   `json:"config,omitempty"`
	CACertificate string   `json:"caCertificate,omitempty"`
	Certificate   string   `json:"certificate,omitempty"`
}

type SecretFile struct {
	Target        string `json:"target"`
	ContentBase64 string `json:"contentBase64"`
}

type AllowedPort struct {
	Protocol     string   `json:"protocol"`
	Port         int      `json:"port"`
	AllowedCIDRs []string `json:"allowedCidrs"`
}

type Probe struct {
	Kind           string `json:"kind"`
	Target         string `json:"target"`
	TimeoutSeconds int    `json:"timeoutSeconds"`
}

type ApplyWorkloadPayload struct {
	EnvironmentID  string            `json:"environmentId"`
	DeploymentID   string            `json:"deploymentId"`
	Generation     int64             `json:"generation"`
	ComposeYAML    string            `json:"composeYaml"`
	ResolvedImages map[string]string `json:"resolvedImages,omitempty"`
	AllowedPorts   []AllowedPort     `json:"allowedPorts,omitempty"`
	SecretFiles    []SecretFile      `json:"secretFiles,omitempty"`
	Probes         []Probe           `json:"probes,omitempty"`
	TimeoutSeconds int               `json:"timeoutSeconds,omitempty"`
}

type CollectObservationPayload struct {
	IncludeWorkloads bool `json:"includeWorkloads"`
}

type RemoveWorkloadPayload struct {
	DeploymentID       string `json:"deploymentId"`
	RemoveOwnedVolumes bool   `json:"removeOwnedVolumes"`
}

type CleanupNodePayload struct {
	EnvironmentID string `json:"environmentId"`
}

type TailWorkloadLogsPayload struct {
	DeploymentID string     `json:"deploymentId"`
	Since        *time.Time `json:"since,omitempty"`
}

type UpgradeAgentPayload struct {
	Version string `json:"version"`
	URL     string `json:"url"`
	SHA256  string `json:"sha256"`
}
